app.py
from flask import Flask, render_template            #flask imports
from views import my_view                           #local imports

app = Flask(__name__)
app.register_blueprint(my_view)                     #Sets the blueprint

@app.errorhandler(404)                              #Error handling belongs in the app.py
def page_not_found(e):                              #Function for error handling. e is the variable for the error message. It is built into flask.
    return render_template("404.html", e=e)         #Redirects to our 404.html

if __name__ == "__main__":
    app.run(debug=True, port=8000)

views.py
from flask import render_template, redirect, Blueprint, url_for

my_view = Blueprint('my_view', __name__)

@my_view.route("/")
def index():
    return render_template("index.html")

@my_view.route("/anthropology")
def anth():
    return render_template("anthropology.html")

@my_view.route("/composite")
def comp():
    return render_template("composite.html")

@my_view.route("/linguistics")
def ling():
    return render_template("linguistics.html")

@my_view.route("/terminology")
def term():
    return render_template("terminology.html")

@my_view.route("/admin")
def admin():
    return render_template("admin.html")

@my_view.route("/rhythm")
def index_redirect():
    return redirect(url_for("my_view.index"))

templates/anthropology.html
{% extends 'base.html' %}

{% block content %}

<h2>Anthropology</h2>

<p>
    In his television series How Music Works, Howard Goodall presents theories that human rhythm recalls the regularity with which we walk and the heartbeat. Other research suggests that it does not relate to the heartbeat directly, but rather the speed of emotional affect, which also influences heartbeat. Yet other researchers suggest that since certain features of human music are widespread, it is "reasonable to suspect that beat-based rhythmic processing has ancient evolutionary roots". Justin London writes that musical metre "involves our initial perception as well as subsequent anticipation of a series of beats that we abstract from the rhythm surface of the music as it unfolds in time". The "perception" and "abstraction" of rhythmic measure is the foundation of human instinctive musical participation, as when we divide a series of identical clock-ticks into "tick-tock-tick-tock".
</p>
<p>
    Joseph Jordania recently suggested that the sense of rhythm was developed in the early stages of hominid evolution by the forces of natural selection. Plenty of animals walk rhythmically and hear the sounds of the heartbeat in the womb, but only humans have the ability to be engaged (entrained) in rhythmically coordinated vocalizations and other activities. According to Jordania, development of the sense of rhythm was central for the achievement of the specific neurological state of the battle trance, crucial for the development of the effective defense system of early hominids. Rhythmic war cry, rhythmic drumming by shamans, rhythmic drilling of the soldiers and contemporary professional combat forces listening to the heavy rhythmic rock music all use the ability of rhythm to unite human individuals into a shared collective identity where group members put the interests of the group above their individual interests and safety.
</p>
<p>
    Some types of parrots can know rhythm. Neurologist Oliver Sacks states that chimpanzees and other animals show no similar appreciation of rhythm yet posits that human affinity for rhythm is fundamental, so that a person's sense of rhythm cannot be lost (e.g. by stroke). "There is not a single report of an animal being trained to tap, peck, or move in synchrony with an auditory beat", Sacks write, "No doubt many pet lovers will dispute this notion, and indeed many animals, from the Lipizzaner horses of the Spanish Riding School of Vienna to performing circus animals appear to 'dance' to music. It is not clear whether they are doing so or are responding to subtle visual or tactile cues from the humans around them."Human rhythmic arts are possibly to some extent rooted in courtship ritual.
</p>
<p>
    The establishment of a basic beat requires the perception of a regular sequence of distinct short-duration pulses and, as a subjective perception of loudness is relative to background noise levels, a pulse must decay to silence before the next occurs if it is to be really distinct. For this reason, the fast-transient sounds of percussion instruments lend themselves to the definition of rhythm. Musical cultures that rely upon such instruments may develop multi-layered polyrhythm and simultaneous rhythms in more than one time signature, called polymeter. Such are the cross-rhythms of Sub-Saharan Africa and the interlocking kotekan rhythms of the gamelan.
</p>
<p>
For information on rhythm in Indian music see Tala (music). For other Asian approaches to rhythm see Rhythm in Persian music, Rhythm in Arabic music and Usul—Rhythm in Turkish music and Dumbek rhythms.
</p>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" media="screen and (orientation: landscape)" href="{{ url_for('static', filename='main.css')}}">
    <link rel="stylesheet" media="screen and (orientation: portrait)" href="{{ url_for('static', filename='mobile.css')}}">
    <script src="{{ url_for('static', filename='app.js')}}"></script>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Rhythm!</title>
</head>
<body>

    <div class="flexlayout">

        <div class="flexnav">
                    <a href="{{ url_for('my_view.index') }}"><div id="logo" class="navlink"><image src="{{url_for('static', filename= 'images/android-chrome-192x192.png')}}"></div></a>
                    <a href="{{ url_for('my_view.index') }}"><div class="navlink">Home</div></a>
                    <a href="{{ url_for('my_view.anth') }}"><div class="navlink">Anthropology</div></a>
                    <a href="{{ url_for('my_view.term') }}"><div class="navlink">Terminology</div></a>
                    <a href="{{ url_for('my_view.comp') }}"><div class="navlink">Composite Rhythm</div></a>
                    <a href="{{ url_for('my_view.ling') }}"><div class="navlink">Linguistics</div></a>
        </div>

        <div class="flexnavb">
            <a href="{{ url_for('my_view.index') }}"><div class="navlink">Home</div></a>
            <a href="{{ url_for('my_view.anth') }}"><div class="navlink">Anthropology</div></a>
            <a href="{{ url_for('my_view.term') }}"><div class="navlink">Terminology</div></a>
            <a href="{{ url_for('my_view.comp') }}"><div class="navlink">Composite Rhythm</div></a>
            <a href="{{ url_for('my_view.ling') }}"><div class="navlink">Linguistics</div></a>
</div>

        <div class="flexmain">

            <div class="flextitle">
                <h1>Rhythm!</h1>
            </div>

            <div class="flexcontent">
                {% block content %}

                {% endblock %}
            </div>
            
            <div class="flextitle">
                <h1>Rhythm!</h1>
            </div>
            
        </div>
    </div>
    



<footer>All information from Wikipedia.</footer>

</body>
</html>

templates/composite.html
{% extends 'base.html' %}

{% block content %}

<h2>Composite Rhythms</h2>
<p>
    A composite rhythm is the durations and patterns (rhythm) produced by amalgamating all sounding parts of a musical texture. In music of the common practice period, the composite rhythm usually confirms the meter, often in metric or even-note patterns identical to the pulse on a specific metric level. White defines composite rhythm as, "the resultant overall rhythmic articulation among all the voices of a contrapuntal texture". This concept was concurrently defined as "attack point rhythm" by Maury Yeston in 1976 as "the extreme rhythmic foreground of a composition – the absolute surface of articulated movement".
</p>

<!-- Enter accordian -->

African music

A Griot performs at Diffa, Niger, West Africa. The Griot is playing a Ngoni or Xalam.
In the Griot tradition of Africa everything related to music has been passed on orally. Babatunde Olatunji (1927–2003) developed a simple series of spoken sounds for teaching the rhythms of the hand-drum, using six vocal sounds, "Goon, Doon, Go, Do, Pa, Ta", for three basic sounds on the drum, each played with either the left or the right hand. The debate about the appropriateness of staff notation for African music is a subject of particular interest to outsiders while African scholars from Kyagambiddwa to Kongo have, for the most part, accepted the conventions and limitations of staff notation, and produced transcriptions to inform and enable discussion and debate.

John Miller has argued that West African music is based on the tension between rhythms, polyrhythms created by the simultaneous sounding of two or more different rhythms, generally one dominant rhythm interacting with one or more independent competing rhythms. These often oppose or complement each other and the dominant rhythm. Moral values underpin a musical system based on repetition of relatively simple patterns that meet at distant cross-rhythmic intervals and on call-and-response form. Collective utterances such as proverbs or lineages appear either in phrases translated into "drum talk" or in the words of songs. People expect musicians to stimulate participation by reacting to people dancing. Appreciation of musicians is related to the effectiveness of their upholding community values.

Indian music
See also: Bol (music)
Indian music has also been passed on orally. Tabla players would learn to speak complex rhythm patterns and phrases before attempting to play them. Sheila Chandra, an English pop singer of Indian descent, made performances based on her singing these patterns. In Indian classical music, the Tala of a composition is the rhythmic pattern over which the whole piece is structured.

Western music
In the 20th century, composers like Igor Stravinsky, Béla Bartók, Philip Glass, and Steve Reich wrote more rhythmically complex music using odd meters, and techniques such as phasing and additive rhythm. At the same time, modernists such as Olivier Messiaen and his pupils used increased complexity to disrupt the sense of a regular beat, leading eventually to the widespread use of irrational rhythms in New Complexity. This use may be explained by a comment of John Cage's where he notes that regular rhythms cause sounds to be heard as a group rather than individually; the irregular rhythms highlight the rapidly changing pitch relationships that would otherwise be subsumed into irrelevant rhythmic groupings. La Monte Young also wrote music in which the sense of a regular beat is absent because the music consists only of long sustained tones (drones). In the 1930s, Henry Cowell wrote music involving multiple simultaneous periodic rhythms and collaborated with Leon Theremin to invent the rhythmicon, the first electronic rhythm machine, in order to perform them. Similarly, Conlon Nancarrow wrote for the player piano.
</p>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<p>
    Rhythm (from Greek ῥυθμός, rhythmos, "any regular recurring motion, symmetry") generally means a "movement marked by the regulated succession of strong and weak elements, or of opposite or different conditions". This general meaning of regular recurrence or pattern in time can apply to a wide variety of cyclical natural phenomena having a periodicity or frequency of anything from microseconds to several seconds (as with the riff in a rock music song); to several minutes or hours, or, at the most extreme, even over many years.
</p>

<image class="splashimg" align="right" src="{{url_for('static', filename= 'images/lee-pigott-OJ4m4_yIgjY-unsplash.jpg')}}">

<p>
    Rhythm is related to and distinguished from pulse, meter, and beats:
</p>

<p>
    Rhythm may be defined as the way in which one or more unaccented beats are grouped in relation to an accented one. ... A rhythmic group can be apprehended only when its elements are distinguished from one another, rhythm...always involves an interrelationship between a single, accented (strong) beat and either one or two unaccented (weak) beats.
</p>

<p>
    In the performance arts, rhythm is the timing of events on a human scale; of musical sounds and silences that occur over time, of the steps of a dance, or the meter of spoken language and poetry. In some performing arts, such as hip hop music, the rhythmic delivery of the lyrics is one of the most important elements of the style. Rhythm may also refer to visual presentation, as "timed movement through space" and a common language of pattern unites rhythm with geometry. For example, architects often speak of the rhythm of a building, referring to patterns in the spacing of windows, columns, and other elements of the façade.[citation needed] In recent years, rhythm and meter have become an important area of research among music scholars. Recent work in these areas includes books by Maury Yeston, Fred Lerdahl and Ray Jackendoff, Jonathan Kramer, Christopher Hasty, Godfried Toussaint, William Rothstein, Joel Lester, and Guerino Mazzola.
</p>

{% endblock %}

templates/linguistics.html
{% extends 'base.html' %}

{% block content %}

<h2>Linguistics</h2>

<p>
In linguistics, rhythm or isochrony is one of the three aspects of prosody, along with stress and intonation. Languages can be categorized according to whether they are syllable-timed, mora-timed, or stress-timed. Speakers of syllable-timed languages such as Spanish and Cantonese put roughly equal time on each syllable; in contrast, speakers of stressed-timed languages such as English and Mandarin Chinese put roughly equal time lags between stressed syllables, with the timing of the unstressed syllables in between them being adjusted to accommodate the stress timing.
</p>
<p>
Narmour describes three categories of prosodic rules that create rhythmic successions that are additive (same duration repeated), cumulative (short-long), or countercumulative (long-short). Cumulation is associated with closure or relaxation, countercumulation with openness or tension, while additive rhythms are open-ended and repetitive. Richard Middleton points out this method cannot account for syncopation and suggests the concept of transformation.
</p>
{% endblock %}

templates/terminology.html
{% extends 'base.html' %}

{% block content %}

<h2>Terminology</h2>

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Pulse, Beat and Measure
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            <blockquote>As a piece of music unfolds, its rhythmic structure is perceived not as a series of discrete independent units strung together in a mechanical, additive, way like beads [or "pulses"], but as an organic process in which smaller rhythmic motives, whole possessing a shape and structure of their own, also function as integral parts of a larger ["architectonic"] rhythmic organization.</blockquote>
            <p>
            Most music, dance and oral poetry establishes and maintains an underlying "metric level", a basic unit of time that may be audible or implied, the pulse or tactus of the mensural level, or beat level, sometimes simply called the beat. This consists of a (repeating) series of identical yet distinct periodic short-duration stimuli perceived as points in time. The "beat" pulse is not necessarily the fastest or the slowest component of the rhythm but the one that is perceived as fundamental: it has a tempo to which listeners entrain as they tap their foot or dance to a piece of music. It is currently most often designated as a crotchet or quarter note in western notation (see time signature). Faster levels are division levels, and slower levels are multiple levels. Maury Yeston clarified "Rhythms of recurrence" arise from the interaction of two levels of motion, the faster providing the pulse and the slower organizing the beats into repetitive groups. "Once a metric hierarchy has been established, we, as listeners, will maintain that organization as long as minimal evidence is present".
        </p>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Unit and gesture
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
            A durational pattern that synchronises with a pulse or pulses on the underlying metric level may be called a rhythmic unit. These may be classified as:<br><br>

            <ul>
              <li>Metric – even patterns, such as steady eighth notes or pulses;</li>
              <li>Intrametric – confirming patterns, such as dotted eighth-sixteenth note and swing patterns;</li>
              <li>Contrametric – non-confirming, or syncopated patterns; and</li>
              <li>Extrametric – irregular patterns, such as tuplets.</li>
            </ul>

            A rhythmic gesture is any durational pattern that, in contrast to the rhythmic unit, does not occupy a period of time equivalent to a pulse or pulses on an underlying metric level. It may be described according to its beginning and ending or by the rhythmic units it contains. Rhythms that begin on a strong pulse are thetic, those beginning on a weak pulse are anacrustic and those beginning after a rest or tied-over note are called initial rest. Endings on a strong pulse are strong, on a weak pulse, weak and those that end on a strong or weak upbeat are upbeat.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingFour">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Alternation and Repetition
        </button>
      </h2>
      <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
        <div class="accordion-body">
              <p>
                Rhythm is marked by the regulated succession of opposite elements: the dynamics of the strong and weak beat, the played beat and the inaudible but implied rest beat, or the long and short note. As well as perceiving rhythm humans must be able to anticipate it. This depends on repetition of a pattern that is short enough to memorize.
              </p>

              <p>
                The alternation of the strong and weak beat is fundamental to the ancient language of poetry, dance and music. The common poetic term "foot" refers, as in dance, to the lifting and tapping of the foot in time. In a similar way musicians speak of an upbeat and a downbeat and of the "on" and "off" beat. These contrasts naturally facilitate a dual hierarchy of rhythm and depend on repeating patterns of duration, accent and rest forming a "pulse-group" that corresponds to the poetic foot. Normally such pulse-groups are defined by taking the most accented beat as the first and counting the pulses until the next accent.Scholes 1977b A rhythm that accents another beat and de-emphasises the downbeat as established or assumed from the melody or from a preceding rhythm is called syncopated rhythm.
              </p>

              <p>
                Normally, even the most complex of meters may be broken down into a chain of duple and triple pulses either by addition or division. According to Pierre Boulez, beat structures beyond four, in western music, are "simply not natural".
              </p>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Tempo and Duration
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <p>
              The tempo of the piece is the speed or frequency of the tactus, a measure of how quickly the beat flows. This is often measured in 'beats per minute' (bpm): 60 bpm means a speed of one beat per second, a frequency of 1 Hz. A rhythmic unit is a durational pattern that has a period equivalent to a pulse or several pulses. The duration of any such unit is inversely related to its tempo.
          </p>
          <p>
              Musical sound may be analyzed on five different time scales, which Moravscik has arranged in order of increasing duration.
          </p>
          <ul>
              <li>Supershort: a single cycle of an audible wave, approximately 1⁄30–1⁄10,000 second (30–10,000 Hz or more than 1,800 bpm). These, though rhythmic in nature, are not perceived as separate events but as continuous musical pitch.</li>
              <li>Short: of the order of one second (1 Hz, 60 bpm, 10–100,000 audio cycles). Musical tempo is generally specified in the range 40 to 240 beats per minute. A continuous pulse cannot be perceived as a musical beat if it is faster than 8–10 per second (8–10 Hz, 480–600 bpm) or slower than 1 per 1.5–2 seconds (0.6–0.5 Hz, 40–30 bpm). Too fast a beat becomes a drone, too slow a succession of sounds seems unconnected. This time frame roughly corresponds to the human heart rate and to the duration of a single step, syllable or rhythmic gesture.</li>
              <li>Medium: ≥ few seconds, this median durational level "defines rhythm in music" as it allows the definition of a rhythmic unit, the arrangement of an entire sequence of accented, unaccented and silent or "rest" pulses into the cells of a measure that may give rise to the "briefest intelligible and self-existent musical unit", a motif or figure. This may be further organized, by repetition and variation, into a definite phrase that may characterise an entire genre of music, dance or poetry and that may be regarded as the fundamental formal unit of music.</li>
              <li>Long: ≥ many seconds or a minute, corresponding to a durational unit that "consists of musical phrases"—which may make up a melody, a formal section, a poetic stanza or a characteristic sequence of dance moves and steps. Thus the temporal regularity of musical organisation includes the most elementary levels of musical form.</li>
              <li>Very long: ≥ minutes or many hours, musical compositions or subdivisions of compositions.</li>
          </ul>
              Curtis Roads takes a wider view by distinguishing nine-time scales, this time in order of decreasing duration. The first two, the infinite and the supra musical, encompass natural periodicities of months, years, decades, centuries, and greater, while the last three, the sample and subsample, which take account of digital and electronic rates "too brief to be properly recorded or perceived", measured in millionths of seconds (microseconds), and finally the infinitesimal or infinitely brief, are again in the extra-musical domain. Roads' Macro level, encompassing "overall musical architecture or form" roughly corresponds to Moravcsik's "very long" division while his Meso level, the level of "divisions of form" including movements, sections, phrases taking seconds or minutes, is likewise similar to Moravcsik's "long" category. Roads' Sound object: "a basic unit of musical structure" and a generalization of note (Xenakis' mini structural time scale); fraction of a second to several seconds, and his Microsound (see granular synthesis) down to the threshold of audible perception; thousandths to millionths of seconds, are similarly comparable to Moravcsik's "short" and "supershort" levels of duration.
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingFive">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          Metric Structure
        </button>
      </h2>
      <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <p>
            The study of rhythm, stress, and pitch in speech is called prosody (see also: prosody (music)): it is a topic in linguistics and poetics, where it means the number of lines in a verse, the number of syllables in each line and the arrangement of those syllables as long or short, accented or unaccented. Music inherited the term "meter or metre" from the terminology of poetry.)
          </p>
          <p>
            The metric structure of music includes meter, tempo and all other rhythmic aspects that produce temporal regularity against which the foreground details or durational patterns of the music are projected. The terminology of western music is notoriously imprecise in this area. MacPherson preferred to speak of "time" and "rhythmic shape", Imogen Holst of "measured rhythm".
          </p>
          <p>
            Dance music has instantly recognizable patterns of beats built upon a characteristic tempo and measure. The Imperial Society of Teachers of Dancing defines the tango, for example, as to be danced in 2
            4 time at approximately 66 beats per minute. The basic slow step forwards or backwards, lasting for one beat, is called a "slow", so that a full "right–left" step is equal to one 2
            4 measure.
          </p>
          <p>
            The general classifications of metrical rhythm, measured rhythm, and free rhythm may be distinguished. Metrical or divisive rhythm, by far the most common in Western music calculates each time value as a multiple or fraction of the beat. Normal accents re-occur regularly providing systematical grouping (measures). Measured rhythm (additive rhythm) also calculates each time value as a multiple or fraction of a specified time unit but the accents do not recur regularly within the cycle. Free rhythm is where there is neither, such as in Christian chant, which has a basic pulse but a freer rhythm, like the rhythm of prose compared to that of verse. See Free time (music).
          </p>
          <p>
            Finally some music, such as some graphically scored works since the 1950s and non-European music such as Honkyoku repertoire for shakuhachi, may be considered ametric. Senza misura is an Italian musical term for "without meter", meaning to play without a beat, using time to measure how long it will take to play the bar.
          </p>
        </div>
      </div>
    </div>
  </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{% endblock %}